
export type OHLC={t:number[];o:number[];h:number[];l:number[];c:number[];v?:number[]};
const BASE=(import.meta as any).env.VITE_API_BASE||'';
function utcMidnight(d:Date){return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));}
function rangeToWindow(range:string,interval:string){const end=utcMidnight(new Date());const start=new Date(end);if(range==='6m')start.setUTCMonth(start.getUTCMonth()-6);else if(range==='3m')start.setUTCMonth(start.getUTCMonth()-3);else if(range==='2y')start.setUTCFullYear(start.getUTCFullYear()-2);else start.setUTCFullYear(start.getUTCFullYear()-1);return {start,end};}
function normalize(j:any):OHLC{const t=(j.t||j.time||[]).map((x:any)=>typeof x==='string'?Date.parse(x):+x);const o=(j.o||j.open||[]).map((x:any)=>+x);const h=(j.h||j.high||[]).map((x:any)=>+x);const l=(j.l||j.low||[]).map((x:any)=>+x);const c=(j.c||j.close||[]).map((x:any)=>+x);const v=(j.v||j.volume||[])?.map((x:any)=>+x)||undefined;const m=new Map<number,number>();for(let i=0;i<t.length;i++){const ts=+t[i];if(Number.isFinite(ts))m.set(ts,i);}const ts=[...m.keys()].sort((a,b)=>a-b);const out:OHLC={t:[],o:[],h:[],l:[],c:[],v:v?[]:undefined};for(const tsVal of ts){const i=m.get(tsVal)!;out.t.push(tsVal);out.o.push(o[i]);out.h.push(h[i]);out.l.push(l[i]);out.c.push(c[i]);if(out.v)(out.v as number[]).push(v![i]||0);}return out;}
export async function fetchOHLCStable(ticker:string,interval:string,range:string){const {start,end}=rangeToWindow(range,interval);const qs=new URLSearchParams({ticker,interval,start:start.toISOString(),end:end.toISOString()}).toString();const url=`${BASE}/api/ohlc?${qs}`;const key=`ohlc:${ticker}:${interval}:${range}`;let cached:null|OHLC=null;try{cached=JSON.parse(localStorage.getItem(key)||'null');}catch{};const r=await fetch(url,{cache:'no-store'}).catch(()=>null);if(r&&r.ok){const j=await r.json();const d=normalize(j);if(d.t.length){localStorage.setItem(key,JSON.stringify(d));return {data:d,source:'api' as const};}}
if(cached)return {data:cached,source:'cache' as const};
throw new Error('no-data');
}
